### ISSUE TITLE
Troubles Building

### ISSUE THREAD

**Issue by dshimo** [appiepollo14/openliberty-realworld-api#22]
I've been struggling to build this project for a bit and decided to call for assistance. From your instructions, I used `docker-compose up -d` to start the PostgreSQL database without issue. Then when running `mvn clean install`, I run into this:

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1367)
	at org.microshed.testing.testcontainers.ApplicationContainer.getDockerImageName(ApplicationContainer.java:626)
	at org.microshed.testing.testcontainers.config.TestcontainersConfiguration.start(TestcontainersConfiguration.java:120)
	at org.microshed.testing.jupiter.MicroShedTestExtension.beforeAll(MicroShedTestExtension.java:70)
	at org.microshed.testing.jupiter.MicroShedTestExtension.beforeAll(MicroShedTestExtension.java:58)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:232)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:152)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:194)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:95)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:40)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
	at org.testcontainers.shaded.com.google.common.util.concurrent.Futures$1.get(Futures.java:536)
	at org.testcontainers.images.RemoteDockerImage.getImageName(RemoteDockerImage.java:130)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:67)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:41)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1365)
	... 5 more

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ArticlesResourceIT » ContainerFetch Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
[ERROR]   ProfilesResourceIT » ContainerFetch Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
[ERROR]   TagsResourceIT » ContainerFetch Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
[ERROR]   UserResourceIT » ContainerFetch Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
[ERROR]   UsersResourceIT » ContainerFetch Can't get Docker image: RemoteDockerImage(imageName=<resolving>, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@be042d4)
[INFO]
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
```

Is there further setup required not mentioned or am I missing something? I've also taken a look into how GitHub actions runs and noticed in the runtime logs that messages like ` [ApplicationContainer] Internal Exception: org.postgresql.util.PSQLException: ERROR: table "tags" does not exist` occur frequently. It may also be worthwhile to run `run-api-tests.sh` to verify the behavior with Conduit's Postman collection.

**Comment by appiepollo14** [comment]
@dshimo Thank you for reaching out. Will look into this issue and get back to you.

**Comment by appiepollo14** [comment]
@dshimo what kind of docker env are you using? 1. The error is clear and related to testcontainers in general, not able to find a docker env. See https://java.testcontainers.org/supported_docker_environment/

2. The errors like: ERROR: relation "comments" does not exist etc. are related to hibernate needing to create those tables and can be ignored. If you've a fix in mind for those errors, please feel free to open a PR.
3. I completely agree to run the api-test. The challenge is that the maven clean install command creates a war-file. How to run this war file in the CI? I've tried starting the app via: `mvn liberty:dev` but than the CI step will never complete and CI will time out after hours and hours.  Again if you have a fix in mind, please feel free to open a PR.

**Comment by dshimo** [comment]
Thanks for the response and help. From your provided link, I additionally had to install `jq` to resolve those env vars. 

3. You can alternatively use `mvn liberty:start` to have Liberty start with the app as a background process. Before running `run-api-tests.sh`, I had to change the endpoint from `localhost:9080/api` to `localhost:9080/realworld-liberty/api` to which I saw passing tests. 
![image](https://github.com/appiepollo14/openliberty-realworld-api/assets/8934136/1b8fa03d-2b1a-42b8-80f1-0016d0b5ebdd)

I wanted to additionally verify the backend with a random frontend, but I'm encountering a usual CORS issue. No worries though.

**Comment by appiepollo14** [comment]
Altered CI to run the api-tests.
